---
- name: Converge
  hosts: all

  pre_tasks:
    - debug: msg="Pre tasks section for {{ ansible_host }}"

    - name: set default facts
      set_fact:
        remote_ip_address: "{{ ansible_host }}"

    - name: Include default vars
      include_vars: "playbook_vars.yml"

  roles:
     - {
        role: "sa-auto-ssh"
       }

#- name: Apply box play
#  import_playbook: ../../playbook.yml

